name: Load project

on:
  workflow_dispatch:

jobs:
  loadForWSAPlayer:
    name: Load for ${{ matrix.targetPlatform }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2020.3.24f1
        targetPlatform:
          #- StandaloneWindows64 # Build a Windows 64-bit standalone.
          - WSAPlayer # Build a UWP App.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: actions/cache@v3
        with:
          path: build/${{ matrix.targetPlatform }}
          key: Build-${{ matrix.targetPlatform }}
          restore-keys: Build-
      - name: Look Around
        run: ls
      - name: Look Around Build
        run: ls build
      - name: Look Around Build/${{ matrix.targetPlatform }}
        run: ls build/${{ matrix.targetPlatform }}
      - name: Look Around Build/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}
        run: ls build/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build Version
        run: |
            msbuild.exe -version
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: 20348
      - name: Install Unity
        run: |
          Install-Module UnitySetup -Force
          Import-Module UnitySetup
          Install-UnitySetupInstance -Cache UnitySetupInstallerCache -Installers (Find-UnitySetupInstaller -Version "${{ matrix.unityVersion }}" -Components 'Windows','Windows_IL2CPP','UWP_IL2CPP') -Verbose
        shell: pwsh
      - name: Cache Unity
        uses: actions/cache@v3
        with:
          path: Library
          key: UnityCache-${{ env.UNITY_VERSION }}
          restore-keys: UnityCache-
      - name: Build Sln
        run: MSBuild build/WSAPlayer/WSAPlayer/MRTK3Demo.sln /nologo /nr:false /p:AppxBundle=Always /p:UapAppxPackageBuildMode=Sideload /p:AppxBundlePlatforms="ARM" /p:AppxPackageDir="./BuildTest" /p:platform="ARM" /p:configuration="Debug"