
name: msbuild

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Create Build Directory
      run: mkdir _build

    - name: Look Around
      run: ls
      
    - name: Build Version1
      run: |
        msbuild.exe -version

    - name: Build Version2
      run: |
        msbuild -version